services:
  db:
    image: db
    build: ./docker/db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  backend:
    image: backend
    build: ./docker/backend
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    image: frontend
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
